<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Capítulo 2 | Apéndices del Libro Pobreza y Desigualdad en R</title>
  <meta name="description" content="Nos propusimos trasncribir al lenguaje R y Python los apéndices del libro Pobreza y Desigualdad en América Latina de Gasparini, Cicowiez y Sosa Escudero que originalmente fueron escritos para Stata." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Capítulo 2 | Apéndices del Libro Pobreza y Desigualdad en R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/portada_libro_cover.png" />
  <meta property="og:description" content="Nos propusimos trasncribir al lenguaje R y Python los apéndices del libro Pobreza y Desigualdad en América Latina de Gasparini, Cicowiez y Sosa Escudero que originalmente fueron escritos para Stata." />
  <meta name="github-repo" content="crisbonavida/Pobreza_Desigualdad_codes" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Capítulo 2 | Apéndices del Libro Pobreza y Desigualdad en R" />
  
  <meta name="twitter:description" content="Nos propusimos trasncribir al lenguaje R y Python los apéndices del libro Pobreza y Desigualdad en América Latina de Gasparini, Cicowiez y Sosa Escudero que originalmente fueron escritos para Stata." />
  <meta name="twitter:image" content="/portada_libro_cover.png" />



<meta name="date" content="2022-02-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="capítulo-3.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Una herramienta práctica para trabajar con datos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Bienvenidos</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#sobre-este-proyecto"><i class="fa fa-check"></i>Sobre este Proyecto:</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#el-libro"><i class="fa fa-check"></i>El Libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#cómo-aprovechar-este-material"><i class="fa fa-check"></i>Cómo aprovechar este material</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#qué-es-y-qué-no-es"><i class="fa fa-check"></i>Qué es y qué no es</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#qué-necesitamos-antes-de-arrancar"><i class="fa fa-check"></i>Qué necesitamos antes de arrancar</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="capítulo-2.html"><a href="capítulo-2.html"><i class="fa fa-check"></i><b>2</b> Capítulo 2</a>
<ul>
<li class="chapter" data-level="" data-path="capítulo-2.html"><a href="capítulo-2.html#set-inicial"><i class="fa fa-check"></i>Set Inicial</a></li>
<li class="chapter" data-level="2.1" data-path="capítulo-2.html"><a href="capítulo-2.html#introducción-ejemplo-brasil"><i class="fa fa-check"></i><b>2.1</b> Introducción: ejemplo Brasil</a></li>
<li class="chapter" data-level="2.2" data-path="capítulo-2.html"><a href="capítulo-2.html#histogramas"><i class="fa fa-check"></i><b>2.2</b> Histogramas</a></li>
<li class="chapter" data-level="2.3" data-path="capítulo-2.html"><a href="capítulo-2.html#función-de-distribución"><i class="fa fa-check"></i><b>2.3</b> Función de distribución</a></li>
<li class="chapter" data-level="2.4" data-path="capítulo-2.html"><a href="capítulo-2.html#pareto"><i class="fa fa-check"></i><b>2.4</b> Pareto</a></li>
<li class="chapter" data-level="2.5" data-path="capítulo-2.html"><a href="capítulo-2.html#box-plot"><i class="fa fa-check"></i><b>2.5</b> Box-plot</a></li>
<li class="chapter" data-level="2.6" data-path="capítulo-2.html"><a href="capítulo-2.html#curva-de-lorenz"><i class="fa fa-check"></i><b>2.6</b> Curva de Lorenz</a></li>
<li class="chapter" data-level="2.7" data-path="capítulo-2.html"><a href="capítulo-2.html#curva-generalizada-de-lorenz"><i class="fa fa-check"></i><b>2.7</b> Curva Generalizada de Lorenz</a></li>
<li class="chapter" data-level="2.8" data-path="capítulo-2.html"><a href="capítulo-2.html#cap-2.8"><i class="fa fa-check"></i><b>2.8</b> Curva de Incidencia</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="capítulo-3.html"><a href="capítulo-3.html"><i class="fa fa-check"></i><b>3</b> Capítulo 3</a>
<ul>
<li class="chapter" data-level="" data-path="capítulo-3.html"><a href="capítulo-3.html#set-inicial-1"><i class="fa fa-check"></i>Set Inicial</a></li>
<li class="chapter" data-level="3.1" data-path="capítulo-3.html"><a href="capítulo-3.html#cociente-de-cuantiles"><i class="fa fa-check"></i><b>3.1</b> Cociente de cuantiles</a></li>
<li class="chapter" data-level="3.2" data-path="capítulo-3.html"><a href="capítulo-3.html#cap-3.2"><i class="fa fa-check"></i><b>3.2</b> Replicar programa ratq51</a></li>
<li class="chapter" data-level="3.3" data-path="capítulo-3.html"><a href="capítulo-3.html#replicar-programa-gcuan"><i class="fa fa-check"></i><b>3.3</b> Replicar programa gcuan</a></li>
<li class="chapter" data-level="3.4" data-path="capítulo-3.html"><a href="capítulo-3.html#tamaño-de-los-hogares"><i class="fa fa-check"></i><b>3.4</b> Tamaño de los hogares</a></li>
<li class="chapter" data-level="3.5" data-path="capítulo-3.html"><a href="capítulo-3.html#la-distribución-intrahogar"><i class="fa fa-check"></i><b>3.5</b> La distribución intrahogar</a></li>
<li class="chapter" data-level="3.6" data-path="capítulo-3.html"><a href="capítulo-3.html#cap-3.6"><i class="fa fa-check"></i><b>3.6</b> Empleo de ponderadores</a></li>
<li class="chapter" data-level="3.7" data-path="capítulo-3.html"><a href="capítulo-3.html#diseño-muestral"><i class="fa fa-check"></i><b>3.7</b> Diseño muestraL</a></li>
<li class="chapter" data-level="3.8" data-path="capítulo-3.html"><a href="capítulo-3.html#fuentes-de-ingreso"><i class="fa fa-check"></i><b>3.8</b> Fuentes de ingreso</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="capítulo-4.html"><a href="capítulo-4.html"><i class="fa fa-check"></i><b>4</b> Capítulo 4</a>
<ul>
<li class="chapter" data-level="" data-path="capítulo-4.html"><a href="capítulo-4.html#set-inicial-2"><i class="fa fa-check"></i>Set Inicial</a></li>
<li class="chapter" data-level="4.1" data-path="capítulo-4.html"><a href="capítulo-4.html#indicador-fgt"><i class="fa fa-check"></i><b>4.1</b> Indicador FGT</a></li>
<li class="chapter" data-level="4.2" data-path="capítulo-4.html"><a href="capítulo-4.html#computar-fgt"><i class="fa fa-check"></i><b>4.2</b> Computar FGT</a></li>
<li class="chapter" data-level="4.3" data-path="capítulo-4.html"><a href="capítulo-4.html#pobreza-relativa"><i class="fa fa-check"></i><b>4.3</b> Pobreza relativa</a></li>
<li class="chapter" data-level="4.4" data-path="capítulo-4.html"><a href="capítulo-4.html#descompoisición-regional-de-la-pobreza"><i class="fa fa-check"></i><b>4.4</b> Descompoisición regional de la pobreza</a></li>
<li class="chapter" data-level="4.5" data-path="capítulo-4.html"><a href="capítulo-4.html#pobreza-según-consumo-e-ingreso"><i class="fa fa-check"></i><b>4.5</b> Pobreza según consumo e ingreso</a></li>
<li class="chapter" data-level="4.6" data-path="capítulo-4.html"><a href="capítulo-4.html#pobreza-por-edad"><i class="fa fa-check"></i><b>4.6</b> Pobreza por edad</a></li>
<li class="chapter" data-level="4.7" data-path="capítulo-4.html"><a href="capítulo-4.html#significatividad-estadistica"><i class="fa fa-check"></i><b>4.7</b> Significatividad estadistica</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="capítulo-5.html"><a href="capítulo-5.html"><i class="fa fa-check"></i><b>5</b> Capítulo 5</a>
<ul>
<li class="chapter" data-level="" data-path="capítulo-5.html"><a href="capítulo-5.html#set-inicial-3"><i class="fa fa-check"></i>Set Inicial</a></li>
<li class="chapter" data-level="5.1" data-path="capítulo-5.html"><a href="capítulo-5.html#pobreza-multidimensional"><i class="fa fa-check"></i><b>5.1</b> Pobreza Multidimensional</a></li>
<li class="chapter" data-level="5.2" data-path="capítulo-5.html"><a href="capítulo-5.html#indice-bourguignon-y-chakravarty-bc---pobreza-multidimensional"><i class="fa fa-check"></i><b>5.2</b> Indice Bourguignon y Chakravarty (BC) - Pobreza Multidimensional</a></li>
<li class="chapter" data-level="5.3" data-path="capítulo-5.html"><a href="capítulo-5.html#indice-alkire-y-foster-af---pobreza-multidimensional"><i class="fa fa-check"></i><b>5.3</b> Indice Alkire y Foster (AF) - Pobreza Multidimensional</a></li>
<li class="chapter" data-level="5.4" data-path="capítulo-5.html"><a href="capítulo-5.html#perfiles-de-pobreza"><i class="fa fa-check"></i><b>5.4</b> Perfiles de Pobreza</a></li>
<li class="chapter" data-level="5.5" data-path="capítulo-5.html"><a href="capítulo-5.html#perfiles-de-pobreza-condicionados"><i class="fa fa-check"></i><b>5.5</b> Perfiles de Pobreza Condicionados</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Apéndices del Libro Pobreza y Desigualdad en R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="capítulo-2" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Capítulo 2</h1>
<div id="herramientas-para-el-análisis-distributivo" class="section level2 unlisted unnumbered">
<h2>Herramientas para el análisis distributivo</h2>
<div id="escrito-por-cristian-bonavida" class="section level4 unnumbered">
<h4>Escrito por: Cristian Bonavida</h4>
</div>
<div id="last-update-0272021" class="section level4 unnumbered">
<h4>Last Update: 02/7/2021</h4>
<p>
 
</p>
<p><em>Códigos escritos en base a los apéndices del libro “Pobreza y Desigualdad en América Latina” de Gasparini, Cicowiez y Sosa Escudero. El objeto de este material es reproducir la rutina de códigos para STATA presentada en el libro al lenguaje R. Este material es solo de caracter complementario a las explicaciones y detalles conceptuales que se presentan en el libro de texto y los apéndices</em></p>
<p>
 
</p>
</div>
</div>
<div id="set-inicial" class="section level2 unnumbered">
<h2>Set Inicial</h2>
<p>Cargo las librerias, limpio environment, defino el path y atajo para función paste</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="capítulo-2.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="capítulo-2.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># Data wrangling</span></span>
<span id="cb1-3"><a href="capítulo-2.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidygraph)</span>
<span id="cb1-4"><a href="capítulo-2.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-5"><a href="capítulo-2.html#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="capítulo-2.html#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreign)</span>
<span id="cb1-7"><a href="capítulo-2.html#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span>
<span id="cb1-8"><a href="capítulo-2.html#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="capítulo-2.html#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())    <span class="co">#empiezo limpiando todo </span></span>
<span id="cb1-10"><a href="capítulo-2.html#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="capítulo-2.html#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="st">&quot;%+%&quot;</span> <span class="ot">&lt;-</span> <span class="cf">function</span>(x,y) <span class="fu">paste</span>(x,y,<span class="at">sep =</span> <span class="st">&quot;&quot;</span>)      <span class="co"># defino un shorcut parar concat de texto</span></span>
<span id="cb1-12"><a href="capítulo-2.html#cb1-12" aria-hidden="true" tabindex="-1"></a>data_dir <span class="ot">&lt;-</span> <span class="st">&quot;C:/Users/HP/Desktop/CEDLAS - UNLP/Apendices en R/Material libro/encuestas-cedlas/Encuestas/&quot;</span>  <span class="co">#seteo directorio </span></span></code></pre></div>
<p>
 
</p>
</div>
<div id="introducción-ejemplo-brasil" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Introducción: ejemplo Brasil</h2>
<p>###- (pág. 72)</p>
<p>El siguiente código es introductorio y busca guiar al lector en la sintaxis básica a utilizar, mostrando a modo de ejemplo cómo replicar los resultados correspondientes al cuadro 2.1 del texto.</p>
<p>Como será al inicio de cada capítulo, el primer paso es obtener base de datos, en ese caso la versión procesada de la PNAD (Pesquisa Nacional por Amostra de Domicílios) de Brasil para el año 2007, accesible desde el link de descarga indicado en la sección anterior: datos y set up básico. (Añadir sección y referir allí)</p>
<p>Una vez descargada la encuesta y guardada en el directorio que el lector indicó al definir el objeto <em>“data_dir”</em> se carga la encuesta que se encuentra en formato STATA con la librería <code>foreing</code>. Dentro de ella el comando <code>read.dta()</code> permite importar en R bases de datos que están en formatos compatibles con otros programas o lenguajes. Las encuestas de hogares procesadas que se utilizan a lo largo del libro solo deben contener observaciones que denominamos coherentes, que en pocas palabras se trata de observaciones válidas que utilizamos en el cálculo de los ingresos familiares. Por ello siempre que se cargue una base luego se debe filtrarla a partir de la columna <em>cohh</em>, para quedarse solo con estas observaciones.</p>
<p>Las encuestas de hogares, al igual que cualquier otra base de datos, se organizan en R como objetos tipo tabla que reciben el nombre de <code>dataframe</code>, donde las filas representan observaciones o registros y las columnas variables o campos. Con el comando <code>head()</code> podemos explorar las primeras observaciones de la encuesta. La expresión <code>[,1:9]</code> indica incluir solo de la columna 1 a 9 para que el output no sea demasiado extenso.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="capítulo-2.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cargo base</span></span>
<span id="cb2-2"><a href="capítulo-2.html#cb2-2" aria-hidden="true" tabindex="-1"></a>bra07 <span class="ot">&lt;-</span> <span class="fu">read.dta</span>(data_dir <span class="sc">%+%</span> <span class="st">&quot;Bra/2007/Bases/bra07_cedlas.dta&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="capítulo-2.html#cb2-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">filter</span>(cohh<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb2-4"><a href="capítulo-2.html#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="capítulo-2.html#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bra07[,<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>])</span></code></pre></div>
<pre><code>##   edad relacion tarea hstrp pondera pais  ano  encuesta id
## 1   73        1    NA    NA     239  bra 2007 PNAD-2007 14
## 2   52        1    NA    NA     238  bra 2007 PNAD-2007 16
## 3   10        4    NA    NA     238  bra 2007 PNAD-2007 16
## 4   34        1    NA    NA     238  bra 2007 PNAD-2007 34
## 5   11        3    NA    NA     238  bra 2007 PNAD-2007 34
## 6   20        4    NA    NA     238  bra 2007 PNAD-2007 34</code></pre>
<p>A su vez, por tratarse de una encuesta, cada observación representa a varios individuos, tantos como indica el factor de expansión o variable de ponderación. En nuestro caso, todas las encuestas que utilizaremos contienen una variable de nombre <em>pondera</em> que almacena el factor de expansión. Para más detalles sobre el uso de ponderadores, consultar más adelante la <a href="capítulo-3.html#cap-3.6">sección 3.6</a></p>
<p>Para expandir las observaciones por su peso muestral debemos emplear alguna de las librerías disponibles creadas para tal fin, ya que “por default” los comandos base de R no estiman estadísticos ponderados, como es el caso por ejemplo del comando <code>summary()</code>. Si se comparan los valores que arroja respecto a los valores de los mismos estadísticos pero ponderados, es evidente que existen diferencias (excepto obviamente para el mínimo y el máximo). Existen varias librerías que nos permiten obtener descriptivos ponderados, aquí se presentan los resultados con el uso de <code>Hmisc</code>, pero también puede explorarse de forma similar las librerías <code>TAM</code> y <code>srvy</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="capítulo-2.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary no arroja estadísticas descriptivas ponderadas</span></span>
<span id="cb4-2"><a href="capítulo-2.html#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bra07<span class="sc">$</span>ipcf)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##     0.0   157.5   310.0   559.1   590.0 66000.0    1057</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="capítulo-2.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#replicar la información que nos da summary pero ponderandola - usando libreria Hmisc</span></span>
<span id="cb6-2"><a href="capítulo-2.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.mean</span>(bra07<span class="sc">$</span>ipcf, <span class="at">w=</span>bra07<span class="sc">$</span>pondera)</span></code></pre></div>
<pre><code>## [1] 574.3455</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="capítulo-2.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wtd.quantile</span>(bra07<span class="sc">$</span>ipcf, <span class="at">probs =</span><span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>) , <span class="at">w=</span>bra07<span class="sc">$</span>pondera)</span></code></pre></div>
<pre><code>##   25%   50%   75% 
## 165.0 330.0 621.5</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="capítulo-2.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(bra07<span class="sc">$</span>ipcf, <span class="at">na.rm =</span>T)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="capítulo-2.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(bra07<span class="sc">$</span>ipcf, <span class="at">na.rm =</span>T)</span></code></pre></div>
<pre><code>## [1] 66000</code></pre>
<p>Mientras que la media no pondera es de 559.1 al ponderar el valor estimado es 574.3
Lo mismo ocurre para la mediana, el primer y el tercer cuartil de la distribución.</p>
<p>Una opción recomendada para usuarios más familiarizados con la sintaxis de R, es definir una función que nos calcule e imprima los resultados para estos estadísticos ponderados de una sola vez, replicando lo que hace <code>summary()</code>. Las funciones son una especie de comando personalizado que nos permiten customizar los cálculos y el output a nuestra necesidad o gusto. -ver <a href="capítulo-3.html#cap-3.2">capitulo siguiente</a> donde nos extendemos sobre el uso de funciones-. En este caso nos permite elegir qué estadisticos queremos calcular y cómo mostrarlos, con una salida que incluye un título junto al resultado númerico mediante la función <code>paste()</code>) y redondeando a un decimal (mediante la función <code>round(..., d=1)</code>)</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="capítulo-2.html#cb14-1" aria-hidden="true" tabindex="-1"></a>my_weighted_stats <span class="ot">&lt;-</span> <span class="cf">function</span>(argumento1, argumento2){</span>
<span id="cb14-2"><a href="capítulo-2.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-3"><a href="capítulo-2.html#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Mean:&quot;</span>, <span class="fu">round</span>( <span class="fu">wtd.mean</span>(argumento1, <span class="at">w=</span>argumento2), <span class="at">d=</span><span class="dv">1</span> )))</span>
<span id="cb14-4"><a href="capítulo-2.html#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Sd:&quot;</span>, <span class="fu">round</span>( <span class="fu">sqrt</span>(<span class="fu">wtd.var</span>(argumento1, <span class="at">w=</span>argumento2)), <span class="at">d=</span><span class="dv">1</span> )))</span>
<span id="cb14-5"><a href="capítulo-2.html#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">round</span>( <span class="fu">wtd.quantile</span>(bra07<span class="sc">$</span>ipcf, <span class="at">probs =</span><span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>) , <span class="at">w=</span>bra07<span class="sc">$</span>pondera), <span class="at">d=</span><span class="dv">1</span> ))</span>
<span id="cb14-6"><a href="capítulo-2.html#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Min:&quot;</span>, <span class="fu">round</span>( <span class="fu">min</span>(argumento1, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="at">d=</span><span class="dv">1</span> )))</span>
<span id="cb14-7"><a href="capítulo-2.html#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;Max:&quot;</span>, <span class="fu">round</span>( <span class="fu">max</span>(argumento1, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="at">d=</span><span class="dv">1</span> )))</span>
<span id="cb14-8"><a href="capítulo-2.html#cb14-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-9"><a href="capítulo-2.html#cb14-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Una vez definida la función debemos llamarla por el nombre indicando sus argumentos. En este caso el primero hace referencia a la variable y el segundo al ponderador. La función devuelve la información que arrojaría el comando <code>summ</code> en STATA ponderando las estimaciones.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="capítulo-2.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">my_weighted_stats</span>(bra07<span class="sc">$</span>ipcf, bra07<span class="sc">$</span>pondera)</span></code></pre></div>
<pre><code>## [1] &quot;Mean: 574.3&quot;
## [1] &quot;Sd: 970.2&quot;
##   25%   50%   75% 
## 165.0 330.0 621.5 
## [1] &quot;Min: 0&quot;
## [1] &quot;Max: 66000&quot;</code></pre>
<p>Una de las principales ventajas de las funciones es que nos permiten replicar los resultados para distintas encuestas o también para distintos subconjuntos de los datos. Por ejemplo, en el caso de la PNAD 2007 de Brasil, la variable <em>region</em> puede tomar los valores 1, 2, 3, 4 o 5 dependiendo de si la observación corresponde a la región Norte, Nordeste, Sudeste, Sur o Centro-Oeste, respectivamente. Así, las líneas siguientes pueden utilizarse para computar los estadísticos para dichas regiones, replicando aquí las columnas “Norte” y “Nordeste” del cuadro 2.1</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="capítulo-2.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">my_weighted_stats</span>(bra07<span class="sc">$</span>ipcf[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>], bra07<span class="sc">$</span>pondera[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>])</span></code></pre></div>
<pre><code>## [1] &quot;Mean: 391&quot;
## [1] &quot;Sd: 753.6&quot;
##   25%   50%   75% 
## 165.0 330.0 621.5 
## [1] &quot;Min: 0&quot;
## [1] &quot;Max: 49591.7&quot;</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="capítulo-2.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">my_weighted_stats</span>(bra07<span class="sc">$</span>ipcf[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">2</span>], bra07<span class="sc">$</span>pondera[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">2</span>])</span></code></pre></div>
<pre><code>## [1] &quot;Mean: 344.7&quot;
## [1] &quot;Sd: 655.9&quot;
##   25%   50%   75% 
## 165.0 330.0 621.5 
## [1] &quot;Min: 0&quot;
## [1] &quot;Max: 30120&quot;</code></pre>
<p>Ahora el argumento no son todas las filas de las columnas <em>ipcf</em> y <em>pondera</em> sino solo aquellas que cumplen con la condición de pertenecer a la región 1 y 2 en cada caso, lo que se instrumenta con el subscript <code>[bra07$region==x]</code>. Esta expresión actúa como filtro, le indica a R considerar los valores de la variable ipcf y pondera que corresponden a observaciones que cumplen la condición sobre la región.</p>
<p>Siguiendo con el cuadro 2.1 del texto, si quisiéramos replicar el coeficiente de variación, ahora que ya sabemos cómo obtener estadísticas ponderadas, se vuelve muy sencillo. Solo basta con definir un objeto que se llame <em>cv</em> y que contenga el cociente entre la media y el desvío estándar.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="capítulo-2.html#cb21-1" aria-hidden="true" tabindex="-1"></a>cv<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">wtd.var</span>(bra07<span class="sc">$</span>ipcf, <span class="at">w=</span>bra07<span class="sc">$</span>pondera)) <span class="sc">/</span> <span class="fu">wtd.mean</span>(bra07<span class="sc">$</span>ipcf, <span class="at">w=</span>bra07<span class="sc">$</span>pondera)</span>
<span id="cb21-2"><a href="capítulo-2.html#cb21-2" aria-hidden="true" tabindex="-1"></a>cv</span></code></pre></div>
<pre><code>## [1] 1.689302</code></pre>
<p>Y si quisiéramos estimarlo para una región en particular solo deberíamos aplicar el subscript de la misma forma que lo hicimos antes.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="capítulo-2.html#cb23-1" aria-hidden="true" tabindex="-1"></a>cv<span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">wtd.var</span>(bra07<span class="sc">$</span>ipcf[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>], <span class="at">w=</span>bra07<span class="sc">$</span>pondera[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>])) <span class="sc">/</span> </span>
<span id="cb23-2"><a href="capítulo-2.html#cb23-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">wtd.mean</span>(bra07<span class="sc">$</span>ipcf[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>], <span class="at">w=</span>bra07<span class="sc">$</span>pondera[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>]) </span>
<span id="cb23-3"><a href="capítulo-2.html#cb23-3" aria-hidden="true" tabindex="-1"></a>cv</span></code></pre></div>
<pre><code>## [1] 1.927285</code></pre>
<p>La primera columna del cuadro 2.1 del texto del libro mostraba además la población de referencia o número de observaciones expandidas. Para calcularlo basta con sumar la columna pondera, es decir sumar a cada persona aumentándola por su factor de expansión. De esta forma vemos que la población de referencia de la PNAD 2007 es 187 millones de personas aproximadamente.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="capítulo-2.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#número de observaciones expandidas</span></span>
<span id="cb25-2"><a href="capítulo-2.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(bra07<span class="sc">$</span>pondera)</span></code></pre></div>
<pre><code>## [1] 187441902</code></pre>
<p>El ejemplo del texto finaliza con el cómputo de la pobreza en Brasil para el año 2007, utilizando una línea de pobreza de 130 reales mensuales. Una forma sencilla de computar la proporción de individuos con ingresos mensuales menores a 130 reales es mediante el bloque de código siguiente, donde primero se genera una variable binaria <em>pobre</em> a partir del comando <code>ifelse()</code>, Este comando asignará el valor 1 cuando el individuo no supere el umbral monetario y 0 en caso contrario. Luego se computa simplemente la media ponderada de esta variable binaria y se imprime el resultado redondeado a 2 decimales.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="capítulo-2.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#identificar individuos pobres</span></span>
<span id="cb27-2"><a href="capítulo-2.html#cb27-2" aria-hidden="true" tabindex="-1"></a>bra07 <span class="ot">&lt;-</span> bra07 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">pobre=</span><span class="fu">ifelse</span>(ipcf<span class="sc">&lt;</span><span class="fl">129.883</span>, <span class="dv">1</span>, <span class="dv">0</span>)) </span>
<span id="cb27-3"><a href="capítulo-2.html#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="capítulo-2.html#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Total país</span></span>
<span id="cb27-5"><a href="capítulo-2.html#cb27-5" aria-hidden="true" tabindex="-1"></a>pobres_pais <span class="ot">=</span> <span class="fu">wtd.mean</span>(bra07<span class="sc">$</span>pobre, bra07<span class="sc">$</span>pondera)</span>
<span id="cb27-6"><a href="capítulo-2.html#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;shr pobres=&quot;</span>, <span class="fu">round</span>(pobres_pais, <span class="at">d=</span><span class="dv">2</span>)))</span></code></pre></div>
<pre><code>## [1] &quot;shr pobres= 0.18&quot;</code></pre>
<p>El mismo resultado podría obtenerse como el cociente de la suma ponderada de personas pobres sobre el total de población.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="capítulo-2.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#otra forma</span></span>
<span id="cb29-2"><a href="capítulo-2.html#cb29-2" aria-hidden="true" tabindex="-1"></a>pobres_pais <span class="ot">=</span> <span class="fu">sum</span>(bra07<span class="sc">$</span>pondera[bra07<span class="sc">$</span>pobre<span class="sc">==</span><span class="dv">1</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)<span class="sc">/</span><span class="fu">sum</span>(bra07<span class="sc">$</span>pondera)</span>
<span id="cb29-3"><a href="capítulo-2.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;shr pobres=&quot;</span>, <span class="fu">round</span>(pobres_pais, <span class="at">d=</span><span class="dv">2</span>)))</span></code></pre></div>
<pre><code>## [1] &quot;shr pobres= 0.18&quot;</code></pre>
<p>Para calcular la tasa de pobreza para una región en vez de todo el país, basta simplemente con filtrar las observaciones.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="capítulo-2.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Region Norte</span></span>
<span id="cb31-2"><a href="capítulo-2.html#cb31-2" aria-hidden="true" tabindex="-1"></a>pobres_norte <span class="ot">=</span> <span class="fu">wtd.mean</span>(bra07<span class="sc">$</span>pobre[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>], bra07<span class="sc">$</span>pondera[bra07<span class="sc">$</span>region<span class="sc">==</span><span class="dv">1</span>])</span>
<span id="cb31-3"><a href="capítulo-2.html#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;shr pobres=&quot;</span>, <span class="fu">round</span>(pobres_norte, <span class="at">d=</span><span class="dv">2</span>)))</span></code></pre></div>
<pre><code>## [1] &quot;shr pobres= 0.26&quot;</code></pre>
</div>
<div id="histogramas" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Histogramas</h2>
<p>###- (pág 76)</p>
<p>Siguiendo al apéndice del libro mostramos como generar una serie visualizaciones que nos ayudan a analizar la distribución de una variable.</p>
<p>Iniciamos con las instrucciones para graficar un histograma de la distribución del ipcf en México para el año 2006 (figuras 2.2 a 2.8 del texto). Al igual que en el ejemplo de Brasil, el lector puede obtener la ENIGH (Encuesta Nacional de Ingresos y Gastos de los Hogares) mexicana de 2006 desde los links de descarga. La misma también cuenta con las variables <em>ipcf</em> y <em>pondera</em> que utilizaremos en lo que resta de este apéndice. Luego de cargar la base nos aseguramos de trabajar solo con las observaciones coherentes y de igual manera eliminamos cualquier valor “missing” o cero de la variable de ingresos.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="capítulo-2.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cargo base</span></span>
<span id="cb33-2"><a href="capítulo-2.html#cb33-2" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> <span class="fu">read.dta</span>(data_dir <span class="sc">%+%</span> <span class="st">&quot;Mex/2006/bases/mex06_cedlas.dta&quot;</span>)  </span>
<span id="cb33-3"><a href="capítulo-2.html#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="capítulo-2.html#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co">#elimino observaciones incoherentes, con ingreso missing o cero</span></span>
<span id="cb33-5"><a href="capítulo-2.html#cb33-5" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(cohh<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(ipcf) <span class="sc">&amp;</span> ipcf<span class="sc">!=</span><span class="dv">0</span>) </span></code></pre></div>
<p>Para graficar optamos por la librería más extendida en uso en R, <code>ggplot2</code>, ya que tiene una enorme variedad de gráficos y posibilidades de personalización, pero al mismo tiempo mantiene un sintaxis común. Para graficar existen básicamente 3 ítems o funciones comunes que todos los gráficos deben tener y que aquí introducimos brevemente:</p>
<ul>
<li><strong><code>ggplot()</code></strong>: Es la función que da inicio al gráfico, indicando que un objeto grafico va a generarse y consta de dos argumentos que debemos especificar siempre:
<ul>
<li>data: como primer argumento debemos pasarle el dataframe o base de datos donde se encuentran las variables a graficar</li>
<li>aes: es el segundo argumento donde indicamos el o los ejes (x e y) y la diversificación de colores, relleno o formas según los grupos en los que se dividen los datos (por ejemplo si fuéramos a graficar líneas de tendencia y quisiéramos obtener una línea de color diferente para cada región, deberíamos especificarlo aquí)</li>
</ul></li>
<li><strong><code>geom_...()</code></strong>: donde los puntos se completan con el tipo de grafico que queremos. Existe una función para cada gráfico. En el caso de un gráfico de líneas será por ejemplo <code>geom_line()</code> y en el caso de un histograma <code>geom_histogram()</code>.</li>
<li><strong>customización</strong>: existe múltiples funciones y casi infinitas combinaciones para adaptar el grafico en sus escalas, colores, títulos, dimensiones, fuente de los ejes, leyendas, faceteado, etc.</li>
</ul>
<p>A continuación, siguiendo estas líneas generales, graficamos un histograma para el ipcf, empleando la función <code>geom_histogram()</code>. Igual que antes, <code>[w=pondera]</code> indica que cada observación de la encuesta debe expandirse según la cantidad de individuos que representa. La opción <code>bins = 100</code> especifica que el histograma debe identificar 100 grupos (100 barras). Por último el termino <code>stat(count) / sum(count)</code> irá dentro de <code>aes()</code> ya que define al eje y, indicando que queremos un histograma en proporciones y no en valores absolutos. Los demás son pequeñas customizaciones de títulos y colores que el lector podrá intuir fácilmente.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="capítulo-2.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.2 - histograma ipcf</span></span>
<span id="cb34-2"><a href="capítulo-2.html#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mex06, </span>
<span id="cb34-3"><a href="capítulo-2.html#cb34-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>ipcf, <span class="at">weight=</span>pondera)) <span class="sc">+</span> </span>
<span id="cb34-4"><a href="capítulo-2.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">100</span>, <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(count) <span class="sc">/</span> <span class="fu">sum</span>(count)),</span>
<span id="cb34-5"><a href="capítulo-2.html#cb34-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-6"><a href="capítulo-2.html#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporción&quot;</span>, <span class="at">x=</span><span class="st">&quot;ingreso per cápita familiar&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" width="80%" /></p>
<p>Con las líneas siguientes se filtra la base para individuos con ipcf menor a 1500 para evitar la típica distorsión generada por los valores extremos.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="capítulo-2.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.3 - histograma ipcf sin outliers</span></span>
<span id="cb35-2"><a href="capítulo-2.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ipcf <span class="sc">&lt;</span> <span class="dv">15000</span>), </span>
<span id="cb35-3"><a href="capítulo-2.html#cb35-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>ipcf, <span class="at">weight=</span>pondera)) <span class="sc">+</span> </span>
<span id="cb35-4"><a href="capítulo-2.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">100</span>, <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(count) <span class="sc">/</span> <span class="fu">sum</span>(count)),</span>
<span id="cb35-5"><a href="capítulo-2.html#cb35-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="capítulo-2.html#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporción&quot;</span>, <span class="at">x=</span><span class="st">&quot;ingreso per cápita familiar&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="80%" /></p>
<p>Las figuras 2.4 y 2.5 del texto pueden replicarse utilizando el bloque de código siguiente. En la primera se grafica el logaritmo de la variable ipcf, agregando simplemente la función <code>log()</code> para el eje x. En la siguiente se incrementa sucesivamente el número de barras del histograma. Para ello podríamos repetir 4 veces el gráfico cambiando solamente la cantidad de bins. Aquí optamos por presentar un solución más elegante en la que generamos los 4 gráficos a partir de un bucle que itera sobre el número de bins deseado. El lector no familiarizado con los bucles puede optar por la primera opción hasta que en los siguientes capítulos presentemos con más detalle cómo se instrumentan iteraciones mediante bucles.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="capítulo-2.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.4 - histograma logaritmo ipcf</span></span>
<span id="cb36-2"><a href="capítulo-2.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06, </span>
<span id="cb36-3"><a href="capítulo-2.html#cb36-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ipcf), <span class="at">weight=</span>pondera)) <span class="sc">+</span> </span>
<span id="cb36-4"><a href="capítulo-2.html#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">100</span>, <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(count) <span class="sc">/</span> <span class="fu">sum</span>(count)),</span>
<span id="cb36-5"><a href="capítulo-2.html#cb36-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="capítulo-2.html#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">15</span>,<span class="dv">5</span>))<span class="sc">+</span></span>
<span id="cb36-7"><a href="capítulo-2.html#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporción&quot;</span>, <span class="at">x=</span><span class="st">&quot;ingreso per cápita familiar&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="80%" /></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="capítulo-2.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.5 - histogramas con diferente cantidad de intervalos</span></span>
<span id="cb37-2"><a href="capítulo-2.html#cb37-2" aria-hidden="true" tabindex="-1"></a>n_bins <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">1000</span>)</span>
<span id="cb37-3"><a href="capítulo-2.html#cb37-3" aria-hidden="true" tabindex="-1"></a>my_graphs <span class="ot">=</span> <span class="fu">list</span>()</span>
<span id="cb37-4"><a href="capítulo-2.html#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="capítulo-2.html#cb37-5" aria-hidden="true" tabindex="-1"></a>i<span class="ot">=</span><span class="dv">1</span></span>
<span id="cb37-6"><a href="capítulo-2.html#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (n <span class="cf">in</span> n_bins){</span>
<span id="cb37-7"><a href="capítulo-2.html#cb37-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb37-8"><a href="capítulo-2.html#cb37-8" aria-hidden="true" tabindex="-1"></a>    my_graphs[[i]] <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mex06, </span>
<span id="cb37-9"><a href="capítulo-2.html#cb37-9" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ipcf), <span class="at">weight=</span>pondera)) <span class="sc">+</span> </span>
<span id="cb37-10"><a href="capítulo-2.html#cb37-10" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">geom_histogram</span>(<span class="at">bins =</span> n, <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">stat</span>(count) <span class="sc">/</span> <span class="fu">sum</span>(count)),</span>
<span id="cb37-11"><a href="capítulo-2.html#cb37-11" aria-hidden="true" tabindex="-1"></a>                               <span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-12"><a href="capítulo-2.html#cb37-12" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">15</span>,<span class="dv">5</span>))<span class="sc">+</span></span>
<span id="cb37-13"><a href="capítulo-2.html#cb37-13" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporción&quot;</span>, <span class="at">x=</span><span class="st">&quot;ingreso per cápita familiar&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-14"><a href="capítulo-2.html#cb37-14" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">ggtitle</span>( n <span class="sc">%+%</span> <span class="st">&quot; intervalos&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-15"><a href="capítulo-2.html#cb37-15" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb37-16"><a href="capítulo-2.html#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="capítulo-2.html#cb37-17" aria-hidden="true" tabindex="-1"></a>  i<span class="ot">=</span>i<span class="sc">+</span><span class="dv">1</span>  </span>
<span id="cb37-18"><a href="capítulo-2.html#cb37-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-19"><a href="capítulo-2.html#cb37-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-20"><a href="capítulo-2.html#cb37-20" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span>  my_graphs[[<span class="dv">1</span>]]</span>
<span id="cb37-21"><a href="capítulo-2.html#cb37-21" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span>  my_graphs[[<span class="dv">2</span>]]</span>
<span id="cb37-22"><a href="capítulo-2.html#cb37-22" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span>  my_graphs[[<span class="dv">3</span>]]</span>
<span id="cb37-23"><a href="capítulo-2.html#cb37-23" aria-hidden="true" tabindex="-1"></a>g4 <span class="ot">&lt;-</span>  my_graphs[[<span class="dv">4</span>]]</span>
<span id="cb37-24"><a href="capítulo-2.html#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="capítulo-2.html#cb37-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb37-26"><a href="capítulo-2.html#cb37-26" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(g1, g2, g3, g4, <span class="at">ncol=</span><span class="dv">2</span>, <span class="at">nrow=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-19-1.png" width="90%" /></p>
<p>Las líneas que siguen grafican, superpuestos, los histogramas suavizados de las funciones de densidad del logaritmo del ipcf para las regiones Noroeste y Sur de México. Para este grafico, dentro de <code>aes()</code> debemos indicar no solo los ejes x e y junto con el ponderador, sino además debemos indicar que queremos que lo diferencia por grupos. Concretamente la opción <code>fill=factor(region)</code> le indica a R que el color de relleno de la curva (“fill”) estará dado por una variable de la base de datos, en este caso la variable “región.” Dado que dicha variable en la base es del tipo numérico, empleamos <code>factor()</code> para tratarla como una categórica. Para graficar una curva de densidad el comando indicado es <code>geom_density()</code>. Habiendo especificado estas opciones R mostrará una curva de densidad para cada región en el mismo gráfico, a partir de una misma variable (ipcf) ponderándola por el factor de expansión.</p>
<p>Al código se agregan algunas customizaciones mas para la densidad: <code>color="black"</code> indica que queremos bordes negros, <code>alpha=0.4</code> indica el grado de transparencia en el relleno (para que al superponer las curvas continúen siendo visibles) y <code>size</code> indica el grosor del borde simplemente. Finalmente, dado que optamos por el color de relleno para diferenciar Noroeste y Sur, controlamos estas leyendas con la opción <code>scale_fill_discrete()</code>. Notar que en la primer línea definimos el objeto <em>“lp”</em> que contiene el valor de la línea de pobreza internacional de USD 2.5 por día por persona para México (en log), que marcamos como una línea vertical en el grafico con <code>geom_vline()</code>.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="capítulo-2.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.7 - histogramas superpuestos por regiones</span></span>
<span id="cb38-2"><a href="capítulo-2.html#cb38-2" aria-hidden="true" tabindex="-1"></a>lp<span class="ot">=</span><span class="fu">log</span>(<span class="fl">608.245</span>)</span>
<span id="cb38-3"><a href="capítulo-2.html#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="capítulo-2.html#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(region<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> region<span class="sc">==</span><span class="dv">6</span>), </span>
<span id="cb38-5"><a href="capítulo-2.html#cb38-5" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ipcf), <span class="at">weight=</span>pondera, <span class="at">fill=</span><span class="fu">factor</span>(region))) <span class="sc">+</span> </span>
<span id="cb38-6"><a href="capítulo-2.html#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size=</span><span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="capítulo-2.html#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(<span class="at">name=</span><span class="st">&quot;Región&quot;</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Noroeste&quot;</span>, <span class="st">&quot;Sur&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb38-8"><a href="capítulo-2.html#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span>lp)  <span class="sc">+</span></span>
<span id="cb38-9"><a href="capítulo-2.html#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;densidad&quot;</span>, <span class="at">x=</span><span class="st">&quot;logaritmo del ingreso per c?pita familiar&quot;</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-20-1.png" width="80%" /></p>
<p>Una de las ventajas de estos histogramas suavizados es facilitar las comparaciones. Como puede verse, las dos distribuciones son claramente diferentes. La distribución del Sur está desplazada a la izquierda, lo que sugiere que en general los individuos de esa región tienen menores ingresos que en el Noroeste y por lo tanto una densidad mayor caerá por debajo de la línea de pobreza fijada en esa región.</p>
<p>Por último, siguiendo la figura 2.6 y 2.8, se presenta un histograma suavizado junto con una distribución normal, con la diferencia de que aquí el histograma representa la densidad y no la frecuencia relativa. En R esta opción demanda algún ajuste extra en los ejes, que aquí a los fines didácticos se omite, pero que el lector podrá replicar fácilmente siguiendo la nota al pie.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="capítulo-2.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.6/2.8 - histograma logaritmo ipcf suavizado</span></span>
<span id="cb39-2"><a href="capítulo-2.html#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06, </span>
<span id="cb39-3"><a href="capítulo-2.html#cb39-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ipcf), <span class="at">weight=</span>pondera)) <span class="sc">+</span> </span>
<span id="cb39-4"><a href="capítulo-2.html#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">100</span>, <span class="fu">aes</span>(<span class="at">y =</span> ..density..), </span>
<span id="cb39-5"><a href="capítulo-2.html#cb39-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;gray&quot;</span>)  <span class="sc">+</span></span>
<span id="cb39-6"><a href="capítulo-2.html#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">kernel=</span><span class="st">&quot;gaussian&quot;</span>, <span class="at">color=</span><span class="st">&quot;blue3&quot;</span>, <span class="at">size=</span><span class="fl">0.7</span>) <span class="sc">+</span>  </span>
<span id="cb39-7"><a href="capítulo-2.html#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporcion&quot;</span>, <span class="at">x=</span><span class="st">&quot;logaritmo del ingreso per capita familiar&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="80%" /></p>
</div>
<div id="función-de-distribución" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Función de distribución</h2>
<p>###- (pág. 78)</p>
<p>En este apartado se muestra cómo pueden graficarse las funciones de distribución presentadas en la sección 2.3.2 del cuerpo principal del capítulo. El primer paso para construir una función de distribución es ordenar (de menor a mayor) las observaciones de la encuestas, según la variable de ingreso elegida, <em>ipcf</em> en nuestro caso. Esto es lo que hacemos en la primera línea. En la línea siguiente se crea la variable <em>shrpop</em> para almacenar la proporción relativa acumulada de la variable <em>pondera</em>, es decir el porcentaje acumulado de la población que representa cada observación junto con todas las anteriores. <em>shrpop</em> tendrá entonces un valor de 100 para la última observación. Para obtener la suma acumulada expandida empleamos el comenado <code>cumsum()</code> y lo dividimos por el total de población expandido que se obtiene con <code>sum()</code>. La función de distribución presenta las variables <em>shrpop</em> e <em>ipcf</em> en los ejes vertical y horizontal, respectivamente, como se indica en <code>aes()</code>, y se se grafica simplemente con una línea, por lo que usamos el comando <code>geom_line()</code>, donde solo especificamos su tamaño o grosor.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="capítulo-2.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ordenar según ipcf</span></span>
<span id="cb40-2"><a href="capítulo-2.html#cb40-2" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(ipcf)</span>
<span id="cb40-3"><a href="capítulo-2.html#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="capítulo-2.html#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co">#población acumulada ordenamiento ipcf</span></span>
<span id="cb40-5"><a href="capítulo-2.html#cb40-5" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">shrpop=</span><span class="fu">cumsum</span>(pondera)<span class="sc">/</span><span class="fu">sum</span>(pondera))</span>
<span id="cb40-6"><a href="capítulo-2.html#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="capítulo-2.html#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.9 - función de distribución acumulada</span></span>
<span id="cb40-8"><a href="capítulo-2.html#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06, <span class="fu">aes</span>(<span class="at">x=</span>ipcf, <span class="at">y=</span>shrpop))<span class="sc">+</span></span>
<span id="cb40-9"><a href="capítulo-2.html#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size=</span><span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb40-10"><a href="capítulo-2.html#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporción&quot;</span>, <span class="at">x=</span><span class="st">&quot;ingreso per cápita familiar&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="80%" /></p>
<p>Nuevamente, la cola superior larga de la distribución vuelve al gráfico poco útil. Para
aliviar este problema las alternativas son o bien truncar los valores superiores del ingreso, o
trabajar en logaritmos. La figura 2.10 muestra ambas alternativas. Para la primera, en vez de establacer una valor arbitrario a mano, calculamos el ingreso del percentil 95 y en base a este umbral filtramos las observaciones.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="capítulo-2.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.10 función de distribución acumulada sin outliers</span></span>
<span id="cb41-2"><a href="capítulo-2.html#cb41-2" aria-hidden="true" tabindex="-1"></a>p95 <span class="ot">=</span> <span class="fu">wtd.quantile</span>(mex06<span class="sc">$</span>ipcf, <span class="at">probs=</span><span class="fl">0.95</span>, <span class="at">w=</span>mex06<span class="sc">$</span>pondera)</span>
<span id="cb41-3"><a href="capítulo-2.html#cb41-3" aria-hidden="true" tabindex="-1"></a>trunca  <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ipcf<span class="sc">&lt;</span>p95), </span>
<span id="cb41-4"><a href="capítulo-2.html#cb41-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">aes</span>(<span class="at">x=</span>ipcf, <span class="at">y=</span>shrpop))<span class="sc">+</span></span>
<span id="cb41-5"><a href="capítulo-2.html#cb41-5" aria-hidden="true" tabindex="-1"></a>           <span class="fu">geom_line</span>(<span class="at">size=</span><span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb41-6"><a href="capítulo-2.html#cb41-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">ggtitle</span>(<span class="st">&quot;Ignora 5% mas rico&quot;</span>)<span class="sc">+</span></span>
<span id="cb41-7"><a href="capítulo-2.html#cb41-7" aria-hidden="true" tabindex="-1"></a>           <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporción&quot;</span>, <span class="at">x=</span><span class="st">&quot;ingreso per cápita familiar&quot;</span>) </span>
<span id="cb41-8"><a href="capítulo-2.html#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="capítulo-2.html#cb41-9" aria-hidden="true" tabindex="-1"></a>logipcf <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mex06, </span>
<span id="cb41-10"><a href="capítulo-2.html#cb41-10" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ipcf), <span class="at">y=</span>shrpop))<span class="sc">+</span></span>
<span id="cb41-11"><a href="capítulo-2.html#cb41-11" aria-hidden="true" tabindex="-1"></a>           <span class="fu">geom_line</span>(<span class="at">size=</span><span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb41-12"><a href="capítulo-2.html#cb41-12" aria-hidden="true" tabindex="-1"></a>           <span class="fu">ggtitle</span>(<span class="st">&quot;Toda la población&quot;</span>) <span class="sc">+</span></span>
<span id="cb41-13"><a href="capítulo-2.html#cb41-13" aria-hidden="true" tabindex="-1"></a>           <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;proporción&quot;</span>, <span class="at">x=</span><span class="st">&quot;ingreso per cápita familiar&quot;</span>)  </span>
<span id="cb41-14"><a href="capítulo-2.html#cb41-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-15"><a href="capítulo-2.html#cb41-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-16"><a href="capítulo-2.html#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(trunca, logipcf, <span class="at">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="80%" /></p>
<p>Se deja como ejercicio para el lector elaborar las otras funciones de distribución presentadas en la sección 2.3.2. Por su parte, la curva de Pen (ver figuras 2.12 y 2.13) se construye igual que la función de distribución pero se grafica invirtiendo los ejes.</p>
</div>
<div id="pareto" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Pareto</h2>
<p>###- (pág. 78)</p>
<p>En esta sección se muestra cómo replicar la figura 2.14 del texto, que muestra los diagramas de Pareto para las regiones Noroeste y Sur de México. El procedimiento es muy similar al caso de la función de distribución ya que en esencia representan lo mismo, de forma distinta. El gráfico de Pareto muestra para cada valor del ingreso x el porcentaje de la población que recibe ingresos superiores a ese valor x, en una escala doble logarítmica. El cambio de escala genera una suerte de zoom óptico sobre los estratos de mayores ingresos, permitiendo un examen más detallado de esa parte de la distribución.</p>
<p>Para graficarlo seguimos los pasos anteriores, pero ahora ordenamos a la población por ingreso dentro de cada región y ya no considerando el total país. Para ello agrupamos las observaciones por región con <code>group_by()</code> previo a calcular el share acumulado, de forma tal que este cálculo se haga solo entre individuos de una misma región. En la siguiente línea se genera la variable <em>lpareto</em> a partir de la variable <em>shrpop</em>, siguiendo la explicación de la sección 2.3.4 del texto. Finalmente se grafica filtrando la base para las regiones de interés y, siguiendo la misma lógica empleada en el grafico de densidad superpuesta, indicamos dentro de <code>aes()</code> la opción <code>linetype</code> para lograr un tipo de línea diferente que distinga a cada región. Notar que aquí también empleamos <code>factor()</code> para tratar esta variable categórica. Por último, con <code>scale_linetype()</code> customizamos las leyendas.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="capítulo-2.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#población acumulada por región</span></span>
<span id="cb42-2"><a href="capítulo-2.html#cb42-2" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">shrpop=</span><span class="fu">cumsum</span>(pondera)<span class="sc">/</span><span class="fu">sum</span>(pondera)) </span>
<span id="cb42-3"><a href="capítulo-2.html#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="capítulo-2.html#cb42-4" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">lpareto=</span><span class="fu">log</span>(<span class="dv">1</span><span class="sc">-</span>shrpop)) </span>
<span id="cb42-5"><a href="capítulo-2.html#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="capítulo-2.html#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.14 - Diagrama de Pareto</span></span>
<span id="cb42-7"><a href="capítulo-2.html#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(region<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> region<span class="sc">==</span><span class="dv">6</span>), </span>
<span id="cb42-8"><a href="capítulo-2.html#cb42-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ipcf), <span class="at">y=</span>lpareto, <span class="at">weight=</span>pondera, <span class="at">linetype=</span><span class="fu">factor</span>(region))) <span class="sc">+</span> </span>
<span id="cb42-9"><a href="capítulo-2.html#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size=</span><span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb42-10"><a href="capítulo-2.html#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype</span>(<span class="at">name=</span><span class="st">&quot;Región&quot;</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Noroeste&quot;</span>, <span class="st">&quot;Sur&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb42-11"><a href="capítulo-2.html#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;logaritmo del ingreso per cápita familiar&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="80%" /></p>
<p>Las líneas siguientes repiten el ejercicio pero dejando de lado al 1% más rico de la poblacion en cada región. Aquí en vez de filtrar en base al valor de ingresos, lo hacemos en base al porcentaje acumulado, como alternativa al caso anterior.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="capítulo-2.html#cb43-1" aria-hidden="true" tabindex="-1"></a>cutoff<span class="ot">=</span><span class="fl">0.99</span></span>
<span id="cb43-2"><a href="capítulo-2.html#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="capítulo-2.html#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>((region<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> region<span class="sc">==</span><span class="dv">6</span>) <span class="sc">&amp;</span> (shrpop<span class="sc">&lt;=</span>cutoff)),</span>
<span id="cb43-4"><a href="capítulo-2.html#cb43-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">log</span>(ipcf), <span class="at">y=</span>lpareto, <span class="at">weight=</span>pondera, <span class="at">linetype=</span><span class="fu">factor</span>(region))) <span class="sc">+</span> </span>
<span id="cb43-5"><a href="capítulo-2.html#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size=</span><span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="capítulo-2.html#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype</span>(<span class="at">name=</span><span class="st">&quot;Región&quot;</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Noroeste&quot;</span>, <span class="st">&quot;Sur&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb43-7"><a href="capítulo-2.html#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;logaritmo del ingreso per cápita familiar&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-25-1.png" width="80%" /></p>
</div>
<div id="box-plot" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Box-plot</h2>
<p>###- (pág. 79)</p>
<p>Aquí se muestra cómo elaborar diagramas de caja o box-plot como los presentados en la sección 2.3.5 del texto. En este caso haremos una excepción y presentamos primero una alternativa más directa a <code>ggplot</code> que permite manejar facilmente los outliers, a partir de la libreria base de R. El grafico 2.17 retoma la sintaxís habitual de ggplot para costruir un box-plot para cada región. El lector podrá entender rapidamente el código en ambos casos. En el gráfico conjunto, al igual que antes, diferenciamos a las regiones por el color de relleno en cada box, especificando la opción <code>fill</code> y empleamos <code>factor()</code> para tratar a la variable como categórica. Dado que en este caso la vaiable irá en el eje x diferenciando a las regiones, le agregamos las labels correspondientes con la función <code>scale_x_discrete()</code>. La opción <code>alpha=</code> la utilizamos para darle transparencia al relleno y <code>legend.position=none</code> para omitir la leyenda de cada color.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="capítulo-2.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Una opción mas directa fuera de ggplot</span></span>
<span id="cb44-2"><a href="capítulo-2.html#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="capítulo-2.html#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.15 - Box Plot excluyendo outliers</span></span>
<span id="cb44-4"><a href="capítulo-2.html#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(mex06<span class="sc">$</span>ipcf, <span class="at">outline =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-26-1.png" width="80%" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="capítulo-2.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.16 - Box Plot en log con outliers</span></span>
<span id="cb45-2"><a href="capítulo-2.html#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">log</span>(mex06<span class="sc">$</span>ipcf), <span class="at">outline =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-26-2.png" width="80%" /></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="capítulo-2.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.17  - Box Plot en log por regiones con outliers</span></span>
<span id="cb46-2"><a href="capítulo-2.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(region<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> region<span class="sc">==</span><span class="dv">6</span>), </span>
<span id="cb46-3"><a href="capítulo-2.html#cb46-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(region), <span class="at">y=</span><span class="fu">log</span>(ipcf), <span class="at">weight=</span>pondera, <span class="at">fill=</span><span class="fu">factor</span>(region))) <span class="sc">+</span> </span>
<span id="cb46-4"><a href="capítulo-2.html#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb46-5"><a href="capítulo-2.html#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;none&quot;</span>) <span class="sc">+</span> </span>
<span id="cb46-6"><a href="capítulo-2.html#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Noroeste&quot;</span>,<span class="st">&quot;Sur&quot;</span>)) <span class="sc">+</span></span>
<span id="cb46-7"><a href="capítulo-2.html#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Región&quot;</span>, <span class="at">y =</span><span class="st">&quot;log ipcf&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-26-3.png" width="80%" /></p>
</div>
<div id="curva-de-lorenz" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Curva de Lorenz</h2>
<p>###- (pág. 80)</p>
<p>En este apartado se muestra cómo pueden construirse las curvas de Lorenz introducidas en la sección 2.3.6 del capítulo. El primer paso consiste en ordenar a los individuos de menor a mayor según su ingreso, en nuestro caso contenido en la variable ipcf. Para ellos aplicamos la función <code>arrange()</code>. Notar que previo a esto se aplica la función <code>ungroup()</code>, lo cual es siempre recomendable cuando en la misma base ya se había realizado una agrupación, para de alguna forma “resetear” ese agrupamiento previo. Las líneas siguientes generan la variable <em>shrpop</em> de la misma forma en la que fue generada más arriba, estimando la proporción de la población que se acumula hasta cada observación de la encuesta. La diferencia es que ahora también generaremos una variable <em>shrinc</em> que contiene la proporción del ingreso que se acumula hasta cada observación y que se estima expandiendo el ingreso por el ponderador, es decir multiplicando ambas columnas, como puede verse en el código.</p>
<p>La curva de Lorenz nos muestra qué porcentaje de la población acumula un dado porcentaje del ingreso total. Para visualizarlo indicamos entonces los ejes respectivos para <em>shrpop</em> y <em>shrinc</em> y luego aplicamos un gráfico de línea con <code>geom_line()</code>.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="capítulo-2.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ordenar según ipcf</span></span>
<span id="cb47-2"><a href="capítulo-2.html#cb47-2" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(ipcf)</span>
<span id="cb47-3"><a href="capítulo-2.html#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="capítulo-2.html#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co">#población e ingreso acumulado</span></span>
<span id="cb47-5"><a href="capítulo-2.html#cb47-5" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">shrpop=</span><span class="fu">cumsum</span>(pondera)<span class="sc">/</span><span class="fu">sum</span>(pondera),</span>
<span id="cb47-6"><a href="capítulo-2.html#cb47-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">shrinc=</span><span class="fu">cumsum</span>(ipcf<span class="sc">*</span>pondera)<span class="sc">/</span><span class="fu">sum</span>(ipcf<span class="sc">*</span>pondera)) </span>
<span id="cb47-7"><a href="capítulo-2.html#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="capítulo-2.html#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.18 - curva de Lorenz </span></span>
<span id="cb47-9"><a href="capítulo-2.html#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06, <span class="fu">aes</span>(<span class="at">x=</span>shrpop, <span class="at">y=</span>shrinc)) <span class="sc">+</span></span>
<span id="cb47-10"><a href="capítulo-2.html#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-27-1.png" width="80%" /></p>
<p>En las líneas siguientes se comparan las curvas de Lorenz para dos regiones de México. El código sigue los mismos pasos que antes pero ahora los cálculos de población e ingreso acumulado se realizan por región, agregando un <code>group_by()</code>. En el gráfico filtramos las regiones en cuestión y las diferenciamos con distintos tipos de líneas con la opción <em>linetype</em>, al igual que antes. Con <code>theme_bw()</code>, elegimos una temática diferente para modificar un poco el aspecto visual del gráfico.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="capítulo-2.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ordenar según ipcf + región y acumular por región</span></span>
<span id="cb48-2"><a href="capítulo-2.html#cb48-2" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(region, ipcf) <span class="sc">%&gt;%</span> </span>
<span id="cb48-3"><a href="capítulo-2.html#cb48-3" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb48-4"><a href="capítulo-2.html#cb48-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">mutate</span>(<span class="at">shrpop=</span><span class="fu">cumsum</span>(pondera)<span class="sc">/</span><span class="fu">sum</span>(pondera),</span>
<span id="cb48-5"><a href="capítulo-2.html#cb48-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">shrinc=</span><span class="fu">cumsum</span>(ipcf<span class="sc">*</span>pondera)<span class="sc">/</span><span class="fu">sum</span>(ipcf<span class="sc">*</span>pondera)) </span>
<span id="cb48-6"><a href="capítulo-2.html#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="capítulo-2.html#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.19 - curva de lorenz por regiones</span></span>
<span id="cb48-8"><a href="capítulo-2.html#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(region<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> region<span class="sc">==</span><span class="dv">6</span>),</span>
<span id="cb48-9"><a href="capítulo-2.html#cb48-9" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>shrpop, <span class="at">y=</span>shrinc, <span class="at">linetype=</span><span class="fu">factor</span>(region))) <span class="sc">+</span></span>
<span id="cb48-10"><a href="capítulo-2.html#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb48-11"><a href="capítulo-2.html#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype</span>(<span class="at">name=</span><span class="st">&quot;Region&quot;</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Noroeste&quot;</span>, <span class="st">&quot;Sur&quot;</span>)) <span class="sc">+</span></span>
<span id="cb48-12"><a href="capítulo-2.html#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-28-1.png" width="80%" /></p>
</div>
<div id="curva-generalizada-de-lorenz" class="section level2" number="2.7">
<h2><span class="header-section-number">2.7</span> Curva Generalizada de Lorenz</h2>
<p>###- (pág. 81)</p>
<p>La curva generalizada de Lorenz se construye a partir de la curva de Lorenz pero multiplicando su eje vertical por el ingreso promedio (ver sección 2.3.6 en el cuerpo del capítulo). Las líneas de código no se modifican respecto de las utilizadas para estimar la curva de Lorenz, salvo en que ahora la variable <em>shrpop</em> la generamos sobre la base de la variable <em>pondera</em>. Para entender el álgebra detrás de esta forma de calcular la curva generalizada de Lorenz, el lector puede remitirse a los apéndices del libro (pagina 81-82) donde queda claramente explicitado. Recordar que la curva generalizada de Lorenz muestra el ingreso acumulado en el x% más pobre de la población, sobre el número de personas. Como quedará mas claro en los capítulos 6 y 7, mientras que la curva de Lorenz se emplea para estudiar desigualdad, la generalizada de Lorenz es muy útil para analizar bienestar agregado.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="capítulo-2.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ordenar según ipcf + región y acumular por región</span></span>
<span id="cb49-2"><a href="capítulo-2.html#cb49-2" aria-hidden="true" tabindex="-1"></a>mex06 <span class="ot">&lt;-</span> mex06 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(region, ipcf) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="capítulo-2.html#cb49-3" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="capítulo-2.html#cb49-4" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">mutate</span>(<span class="at">shrpop=</span><span class="fu">cumsum</span>(pondera)<span class="sc">/</span><span class="fu">sum</span>(pondera),</span>
<span id="cb49-5"><a href="capítulo-2.html#cb49-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">glorenz=</span><span class="fu">cumsum</span>(ipcf<span class="sc">*</span>pondera)<span class="sc">/</span><span class="fu">sum</span>(pondera)) </span>
<span id="cb49-6"><a href="capítulo-2.html#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="capítulo-2.html#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.20 - curva de Lorenz generalizada por regiones</span></span>
<span id="cb49-8"><a href="capítulo-2.html#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mex06 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(region<span class="sc">==</span><span class="dv">1</span> <span class="sc">|</span> region<span class="sc">==</span><span class="dv">6</span>),</span>
<span id="cb49-9"><a href="capítulo-2.html#cb49-9" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>shrpop, <span class="at">y=</span>glorenz, <span class="at">linetype=</span><span class="fu">factor</span>(region))) <span class="sc">+</span></span>
<span id="cb49-10"><a href="capítulo-2.html#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb49-11"><a href="capítulo-2.html#cb49-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype</span>(<span class="at">name=</span><span class="st">&quot;Region&quot;</span>, <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Noroeste&quot;</span>, <span class="st">&quot;Sur&quot;</span>)) <span class="sc">+</span></span>
<span id="cb49-12"><a href="capítulo-2.html#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-29-1.png" width="80%" /></p>
</div>
<div id="cap-2.8" class="section level2" number="2.8">
<h2><span class="header-section-number">2.8</span> Curva de Incidencia</h2>
<p>###- (pág. 83)</p>
<p>En este apartado se muestra cómo pueden estimarse las curvas de incidencia del crecimiento que aparecen en la figura 2.21 del texto. A modo de ejemplo, se computa la curva de incidencia del crecimiento para Argentina entre 1992 y 2006, utilizando percentiles del ingreso per cápita familiar. Para ello el lector deberá descargar dichas bases en su directorio de trabajo.</p>
<p>La idea básica será generar un bucle que en cada repetición cargue una base, la ordene por ipcf, genere el porcentaje de población acumulado, en base a este identifique el percentil de ingreso que corresponde y finalmente estime la media del ingreso en percentil. Dado que tenemos dos bases distintas, el bucle iterará dos veces.</p>
<p>Para implementarlo se propone utilizar una lista (objeto tipo <em>list</em>), en la que la EPH de cada año va a ser un elemento distinto. Así el primer elemento de esa lista corresponderá a toda la base de 1992 y el segundo, a toda la base del 2006. Para señalar el primer y segundo elemento nos valemos de un contador <em>i</em> que en la primer iteración del bucle valdrá uno, y al que iremos sumando de uno en uno, por lo que en la segunda tomará valor dos. Por eso la expresión <code>bases_mod[[i]]</code> será equivalente a decir “elemento 1 de la lista <em>bases_mod</em>” en la primera iteración y “elemento 2 de la lista <em>bases_mod</em>” en la segunda iteración. Con esto logramos que en vez de ordenar, generar y cambiar variables sobre un dataframe estático, lo hagamos sucesivamente sobre dataframes distintos contenidos en un lista “madre,” que aquí llamamos <em>bases_mod</em>.</p>
<p>Nuestro bucle irá iterando sobre <em>j</em>, que al igual que <em>i</em> cambiará de valor en cada vuelta. En la primera será 92 y en la segunda 06 y nos servirá para indicar con qué base trabajar. Así <code>read.dta()</code> tiene como argumento la función <code>paste()</code> que une el prefijo <em>“arg”</em> al año de la base correspondiente (<em>j</em>), generando, junto con el prefijo <em>“dta”</em>, un string igual al nombre de la base completa. De esta forma logramos cambiar el nombre en cada iteración para cargar bases de años diferentes.</p>
<p>Dado que estamos trabajando con años distintos debemos prever que necesitaremos ajustar los valores de ingresos por inflación. Por eso en caso de que la base sea la del 92, se multiplica el ipcf por el factor de ajuste (2.099). Esto se debe hacer solo en el caso de la base de 1992 y la manera de instrumentarlo es diciéndole a R que ese cambio debe realizarse solo cuando j sea igual a 92 -<code>if (j=="92")</code>-.</p>
<p>Una vez cargada la base, logrado el ajuste por inflación, aplicamos los mismos pasos que antes para ordenar por ipcf a la población y calcular el porcentaje acumulado. Con ese porcentaje acumulado generaremos los percentiles anidando un bucle a nuestro bucle inicial, que hará 100 repeticiones en cada EPH. En cada una de ellas asignará los percentiles en base a <em>shrpop</em> ayudándose de la variable <em>z</em> multiplicada por 0.01. La razón es sencilla: si queremos generar percentiles (n=100), necesitamos 100 cuantiles por lo que cada cuantil se asigna de a intervalos de población acumulada iguales a 0.01 (1/100). Así por ejemplo, cuando z sea igual a 20, <code>(z-1)*0.01</code> será igual a 0.19 y <code>z*0.01</code> a 0.20, por lo que caerán en este cuantil veinte, todos aquellos individuos que ordenados por ingreso, estén entre el 19 y el 20 por ciento de población acumulada. Dado que empleamos el comando <code>ifelse()</code>, para las obserservaciones restantes que caen fuera de este intervalo, se mantendrá el valor que ya traía la variable <em>“percentil”</em>. Es por esto que antes del bucle, la generamos como vacía, para luego ir rellenándola sucesivamente. <em>z</em> continuará incrementándose de a uno, hasta llegar a 100, donde asigne el último percentil a aquellas personas que quedaron ultimas en nuestra ordenación, ya que poseían los ingresos mas alto. Al considerar a este 1% de la población faltante, se habrá acumulado al 100%. Finalmente el último paso, consiste en reducir todo el dataframe a 100 observaciones correspondientes a los 100 percentiles recién creados y calcular la media del ingreso de las personas que pertenezcan a cada percentil.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="capítulo-2.html#cb50-1" aria-hidden="true" tabindex="-1"></a>bases_mod <span class="ot">&lt;-</span> <span class="fu">list</span>() <span class="co">#lista vacia en la que se guardaran los cambios</span></span>
<span id="cb50-2"><a href="capítulo-2.html#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="capítulo-2.html#cb50-3" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="dv">1</span>              <span class="co">#contador para iterar sobre los elementos de la lista</span></span>
<span id="cb50-4"><a href="capítulo-2.html#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="capítulo-2.html#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="co">#j tomará valor 92 y 06</span></span>
<span id="cb50-6"><a href="capítulo-2.html#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">c</span>(<span class="st">&quot;92&quot;</span>,<span class="st">&quot;06&quot;</span>)){     </span>
<span id="cb50-7"><a href="capítulo-2.html#cb50-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-8"><a href="capítulo-2.html#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#cargo base</span></span>
<span id="cb50-9"><a href="capítulo-2.html#cb50-9" aria-hidden="true" tabindex="-1"></a>  bases_mod[[i]] <span class="ot">&lt;-</span> <span class="fu">read.dta</span>(data_dir <span class="sc">%+%</span> <span class="fu">paste</span>(<span class="st">&quot;Arg/bases/arg&quot;</span>,j,<span class="st">&quot;_cedlas.dta&quot;</span>, <span class="at">sep =</span><span class="st">&quot;&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb50-10"><a href="capítulo-2.html#cb50-10" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">filter</span>(cohh<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(ipcf) <span class="sc">&amp;</span> ipcf<span class="sc">!=</span><span class="dv">0</span>)</span>
<span id="cb50-11"><a href="capítulo-2.html#cb50-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-12"><a href="capítulo-2.html#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="co">#ajuste por inflación para el año 92 solamente</span></span>
<span id="cb50-13"><a href="capítulo-2.html#cb50-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (j<span class="sc">==</span><span class="st">&quot;92&quot;</span>){</span>
<span id="cb50-14"><a href="capítulo-2.html#cb50-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb50-15"><a href="capítulo-2.html#cb50-15" aria-hidden="true" tabindex="-1"></a>      bases_mod[[i]] <span class="ot">&lt;-</span> bases_mod[[i]] <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">ipcf=</span>ipcf<span class="sc">*</span><span class="fl">2.099</span>)</span>
<span id="cb50-16"><a href="capítulo-2.html#cb50-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb50-17"><a href="capítulo-2.html#cb50-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb50-18"><a href="capítulo-2.html#cb50-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-19"><a href="capítulo-2.html#cb50-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#ordenar según ipcf</span></span>
<span id="cb50-20"><a href="capítulo-2.html#cb50-20" aria-hidden="true" tabindex="-1"></a>  bases_mod[[i]] <span class="ot">&lt;-</span> bases_mod[[i]] <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(ipcf)</span>
<span id="cb50-21"><a href="capítulo-2.html#cb50-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-22"><a href="capítulo-2.html#cb50-22" aria-hidden="true" tabindex="-1"></a>  <span class="co">#computar porcentaje de población</span></span>
<span id="cb50-23"><a href="capítulo-2.html#cb50-23" aria-hidden="true" tabindex="-1"></a>  bases_mod[[i]] <span class="ot">&lt;-</span> bases_mod[[i]] <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">shrpop=</span><span class="fu">cumsum</span>(pondera)<span class="sc">/</span><span class="fu">sum</span>(pondera))</span>
<span id="cb50-24"><a href="capítulo-2.html#cb50-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-25"><a href="capítulo-2.html#cb50-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">#identificar percentil de ipcf</span></span>
<span id="cb50-26"><a href="capítulo-2.html#cb50-26" aria-hidden="true" tabindex="-1"></a>  bases_mod[[i]] <span class="ot">&lt;-</span> bases_mod[[i]] <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">percentile=</span><span class="dv">0</span>)  <span class="co">#esto es equivalente a gen percentile=. en stata</span></span>
<span id="cb50-27"><a href="capítulo-2.html#cb50-27" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb50-28"><a href="capítulo-2.html#cb50-28" aria-hidden="true" tabindex="-1"></a>      <span class="cf">for</span> (z <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){  <span class="co">#bucle anidado: itera 100 veces para cada una de las bases </span></span>
<span id="cb50-29"><a href="capítulo-2.html#cb50-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb50-30"><a href="capítulo-2.html#cb50-30" aria-hidden="true" tabindex="-1"></a>        bases_mod[[i]] <span class="ot">&lt;-</span> bases_mod[[i]] <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">percentile=</span><span class="fu">ifelse</span>((shrpop<span class="sc">&gt;</span>(z<span class="dv">-1</span>)<span class="sc">*</span><span class="fl">0.01</span> <span class="sc">&amp;</span> shrpop<span class="sc">&lt;=</span>z<span class="sc">*</span><span class="fl">0.01</span>), z, percentile)) </span>
<span id="cb50-31"><a href="capítulo-2.html#cb50-31" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb50-32"><a href="capítulo-2.html#cb50-32" aria-hidden="true" tabindex="-1"></a>      }  </span>
<span id="cb50-33"><a href="capítulo-2.html#cb50-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-34"><a href="capítulo-2.html#cb50-34" aria-hidden="true" tabindex="-1"></a>  bases_mod[[i]] <span class="ot">&lt;-</span> bases_mod[[i]] <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(percentile) <span class="sc">%&gt;%</span> </span>
<span id="cb50-35"><a href="capítulo-2.html#cb50-35" aria-hidden="true" tabindex="-1"></a>                                       <span class="fu">summarise</span>(<span class="at">ipcf=</span><span class="fu">wtd.mean</span>(ipcf, <span class="at">w=</span>pondera, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb50-36"><a href="capítulo-2.html#cb50-36" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-37"><a href="capítulo-2.html#cb50-37" aria-hidden="true" tabindex="-1"></a>  i<span class="ot">=</span>i<span class="sc">+</span><span class="dv">1</span>  </span>
<span id="cb50-38"><a href="capítulo-2.html#cb50-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb50-39"><a href="capítulo-2.html#cb50-39" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Cuando el bucle finaliza, podemos “recuperar” como dataframes los elementos almacenados en nuestra lista <em>“bases_mod”</em>. El primero corresponde a los ingresos promedios de cada percentil construidos con la base de 1992 y el segundo con la de 2006.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="capítulo-2.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#recupero las bases de cada año como respectivos elementos de la lista</span></span>
<span id="cb51-2"><a href="capítulo-2.html#cb51-2" aria-hidden="true" tabindex="-1"></a>arg92 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(bases_mod[[<span class="dv">1</span>]])</span>
<span id="cb51-3"><a href="capítulo-2.html#cb51-3" aria-hidden="true" tabindex="-1"></a>arg06 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(bases_mod[[<span class="dv">2</span>]])</span>
<span id="cb51-4"><a href="capítulo-2.html#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="capítulo-2.html#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(arg92)</span></code></pre></div>
<pre><code>##   percentile      ipcf
## 1          1  40.71898
## 2          2  69.34599
## 3          3  84.42000
## 4          4  99.58729
## 5          5 112.42315
## 6          6 122.64216</code></pre>
<p>Para finalizar la estimación, debemos calcular el cambio porcentual en el ingreso promedio de cada percentil entre estos años. Para ello necesitaremos juntar ambos dataframes en un solo, a partir de la variable percentil, que se encuentra en ambos. Con el comando <code>merge()</code> unificamos las bases y le asignamos un sufijo que nos permita identificar cada columna. Hecho esto ya podemos calcular el cambio porcentual en el ipcf promedio y graficarlo para cada percentil.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="capítulo-2.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#junto bases, asigno nombres y calculo el cambio porcentual</span></span>
<span id="cb53-2"><a href="capítulo-2.html#cb53-2" aria-hidden="true" tabindex="-1"></a>change <span class="ot">&lt;-</span> <span class="fu">merge</span>(arg92, arg06, <span class="at">by=</span><span class="st">&quot;percentile&quot;</span>, <span class="at">suffix=</span><span class="fu">c</span>(<span class="st">&quot;_92&quot;</span>, <span class="st">&quot;_06&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb53-3"><a href="capítulo-2.html#cb53-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">mutate</span>(<span class="at">change=</span>( (ipcf_06<span class="sc">/</span>ipcf_92) <span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="dv">100</span>) </span>
<span id="cb53-4"><a href="capítulo-2.html#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="capítulo-2.html#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="capítulo-2.html#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Figura 2.21 - Curva de incidencia ipcf</span></span>
<span id="cb53-7"><a href="capítulo-2.html#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(change,</span>
<span id="cb53-8"><a href="capítulo-2.html#cb53-8" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>percentile, <span class="at">y=</span>change))<span class="sc">+</span></span>
<span id="cb53-9"><a href="capítulo-2.html#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size=</span><span class="fl">1.2</span>, <span class="at">color=</span><span class="st">&quot;darkcyan&quot;</span>) <span class="sc">+</span></span>
<span id="cb53-10"><a href="capítulo-2.html#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb53-11"><a href="capítulo-2.html#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-32-1.png" width="80%" /></p>
<p>En el caso particuar de esta figura, las magnitudes son diferentes a los reportados orginalmente en el capitulo del libro, pero las interpretaciones se mantienen. La tasa de crecimiento del ingreso
real está completamente por debajo del eje horizontal, denotando una pérdida de ingresos reales, que dada la pendiente positiva de la curva implica caídas proporcionales del ingreso más grandes a medida que vamos descendiendo hacia estratos más pobres de la distribución. Es claro que la desigualdad de ingresos debe haber aumentado en Argentina en ese período.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Para explorar una posible manera de plotear histogramas de frecuencia relativa o absoluta junto con un densidad suavizada el lector encontrará util la <a href="https://stackoverflow.com/questions/27611438/density-curve-overlay-on-histogram-where-vertical-axis-is-frequency-aka-count">siguiente entrada</a> de <em>stackoverflow</em>.<a href="capítulo-2.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="capítulo-3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/02-Cap2_html.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
